In [1]:
import sys
sys.path.append('../')

import tquant as tq

from datetime import date
import tensorflow as tf
import pandas as pd
import numpy as np

# Settings

In [2]:
tq.Settings.evaluation_date = date(2024, 4, 30)

calendar = tq.TARGET()
daycounter = tq.DayCounter(tq.DayCounterConvention.Actual360)
evaluation_date = tq.Settings.evaluation_date

# Market

In [3]:
ir_eur_curve_6m = pd.DataFrame(np.array([['CASH', date(2024, 4, 30), date(2024, 5, 6), '3BD', 6, 0.039313111],
                                ['CASH', date(2024, 4, 30), date(2024, 5, 7), '1W', 7, 0.039336813],
                                ['CASH', date(2024, 4, 30), date(2024, 5, 14),
                                    '2W', 14, 0.039370406],
                                ['CASH', date(2024, 4, 30), date(2024, 5, 21),
                                    '3W', 21, 0.039386373],
                                ['CASH', date(2024, 4, 30), date(2024, 5, 30),
                                    '1M', 30, 0.039361],
                                ['CASH', date(2024, 4, 30), date(2024, 6, 28),
                                    '2M', 59, 0.038995],
                                ['CASH', date(2024, 4, 30), date(2024, 7, 30),
                                    '3M', 91, 0.038744],
                                ['CASH', date(2024, 4, 30), date(2024, 8, 30),
                                    '4M', 122, 0.038624],
                                ['CASH', date(2024, 4, 30), date(2024, 9, 30),
                                    '5M', 153, 0.038431],
                                ['CASH', date(2024, 4, 30), date(2024, 10, 30),
                                    '6M', 183, 0.03813],
                                ['FRA', date(2024, 5, 30), date(2024, 12, 30),
                                    'FRA-1M-7M', 244, 0.037456114],
                                ['FRA', date(2024, 6, 28), date(2025, 2, 28),
                                    'FRA-2M-8M', 304, 0.036747956],
                                ['FRA', date(2024, 7, 30), date(2025, 4, 30),
                                    'FRA-3M-9M', 365, 0.036029687],
                                ['FRA', date(2024, 8, 30), date(2025, 6, 30),
                                    'FRA-4M-10M', 426, 0.035404603],
                                ['FRA', date(2024, 9, 30), date(2025, 8, 29),
                                    'FRA-5M-11M', 486, 0.03477227],
                                ['FRA', date(2024, 10, 30), date(2025, 10, 30),
                                    'FRA-6M-12M', 548, 0.034175261],
                                ['FRA', date(2024, 11, 29), date(2025, 12, 29),
                                    'FRA-7M-13M', 608, 0.033631846],
                                ['FRA', date(2024, 12, 30), date(2026, 2, 27),
                                    'FRA-8M-14M', 668, 0.033087195],
                                ['FRA', date(2025, 1, 30), date(2026, 4, 30),
                                    'FRA-9M-15M', 730, 0.032565272],
                                ['FRA', date(2025, 2, 28), date(2026, 6, 29),
                                    'FRA-10M-16M', 790, 0.032101166],
                                ['FRA', date(2025, 3, 31), date(2026, 8, 31),
                                    'FRA-11M-17M', 853, 0.031615746],
                                ['FRA', date(2025, 4, 30), date(2026, 10, 30),
                                    'FRA-12M-18M', 913, 0.031139454],
                                ['FRA', date(2025, 5, 30), date(2026, 12, 30),
                                    'FRA-13M-19M', 974, 0.030782286],
                                ['FRA', date(2025, 6, 30), date(2027, 2, 26),
                                    'FRA-14M-20M', 1032, 0.030476446],
                                ['FRA', date(2025, 7, 30), date(2027, 4, 30),
                                    'FRA-15M-21M', 1095, 0.030112955],
                                ['FRA', date(2025, 8, 29), date(2027, 6, 29),
                                    'FRA-16M-22M', 1155, 0.0297541],
                                ['FRA', date(2025, 9, 30), date(2027, 8, 30),
                                    'FRA-17M-23M', 1217, 0.029378001],
                                ['FRA', date(2025, 10, 30), date(2027, 10, 29),
                                    'FRA-18M-24M', 1277, 0.029061516],
                                ['FRA', date(2026, 4, 30), date(2028, 10, 30),
                                    'FRA-24M-30M', 1644, 0.027628463],
                                ['SWAP', date(2024, 4, 30), date(2027, 4, 30),
                                    '3Y', 1095, 0.03188],
                                ['SWAP', date(2024, 4, 30), date(2028, 4, 28),
                                    '4Y', 1459, 0.03054],
                                ['SWAP', date(2024, 4, 30), date(2029, 4, 30),
                                    '5Y', 1826, 0.02968],
                                ['SWAP', date(2024, 4, 30), date(2030, 4, 30),
                                    '6Y', 2191, 0.02918],
                                ['SWAP', date(2024, 4, 30), date(2031, 4, 30),
                                    '7Y', 2556, 0.0289],
                                ['SWAP', date(2024, 4, 30), date(2032, 4, 30),
                                    '8Y', 2922, 0.02875],
                                ['SWAP', date(2024, 4, 30), date(2033, 4, 29),
                                    '9Y', 3286, 0.02869],
                                ['SWAP', date(2024, 4, 30), date(2034, 4, 28),
                                    '10Y', 3650, 0.02869],
                                ['SWAP', date(2024, 4, 30), date(2035, 4, 30),
                                    '11Y', 4017, 0.028709554],
                                ['SWAP', date(2024, 4, 30), date(2036, 4, 30),
                                    '12Y', 4383, 0.02874],
                                ['SWAP', date(2024, 4, 30), date(2037, 4, 30),
                                    '13Y', 4748, 0.028758942],
                                ['SWAP', date(2024, 4, 30), date(2038, 4, 30),
                                    '14Y', 5113, 0.028755258],
                                ['SWAP', date(2024, 4, 30), date(2039, 4, 29),
                                    '15Y', 5477, 0.02871],
                                ['SWAP', date(2024, 4, 30), date(2040, 4, 30),
                                    '16Y', 5844, 0.028613427],
                                ['SWAP', date(2024, 4, 30), date(2041, 4, 30),
                                    '17Y', 6209, 0.028464075],
                                ['SWAP', date(2024, 4, 30), date(2042, 4, 30),
                                    '18Y', 6574, 0.02827543],
                                ['SWAP', date(2024, 4, 30), date(2043, 4, 30),
                                    '19Y', 6939, 0.02806049],
                                ['SWAP', date(2024, 4, 30), date(2044, 4, 29),
                                    '20Y', 7304, 0.02783],
                                ['SWAP', date(2024, 4, 30), date(2045, 4, 28),
                                    '21Y', 7668, 0.027587082],
                                ['SWAP', date(2024, 4, 30), date(2046, 4, 30),
                                    '22Y', 8035, 0.027338756],
                                ['SWAP', date(2024, 4, 30), date(2047, 4, 30),
                                    '23Y', 8400, 0.027087761],
                                ['SWAP', date(2024, 4, 30), date(2048, 4, 30),
                                    '24Y', 8766, 0.026837677],
                                ['SWAP', date(2024, 4, 30), date(2049, 4, 30),
                                    '25Y', 9131, 0.02659],
                                ['SWAP', date(2024, 4, 30), date(2050, 4, 29),
                                    '26Y', 9495, 0.026346703],
                                ['SWAP', date(2024, 4, 30), date(2051, 4, 28),
                                    '27Y', 9859, 0.026109874],
                                ['SWAP', date(2024, 4, 30), date(2052, 4, 30),
                                    '28Y', 10227, 0.02588184],
                                ['SWAP', date(2024, 4, 30), date(2053, 4, 30),
                                    '29Y', 10592, 0.025660098],
                                ['SWAP', date(2024, 4, 30), date(2054, 4, 30),
                                    '30Y', 10957, 0.02545],
                                ['SWAP', date(2024, 4, 30), date(2055, 4, 30),
                                    '31Y', 11322, 0.025250244],
                                ['SWAP', date(2024, 4, 30), date(2056, 4, 28),
                                    '32Y', 11686, 0.025059878],
                                ['SWAP', date(2024, 4, 30), date(2057, 4, 30),
                                    '33Y', 12053, 0.024875626],
                                ['SWAP', date(2024, 4, 30), date(2058, 4, 30),
                                    '34Y', 12418, 0.024696605],
                                ['SWAP', date(2024, 4, 30), date(2059, 4, 30),
                                    '35Y', 12783, 0.02452],
                                ['SWAP', date(2024, 4, 30), date(2060, 4, 30),
                                    '36Y', 13149, 0.02434789],
                                ['SWAP', date(2024, 4, 30), date(2061, 4, 29),
                                    '37Y', 13513, 0.024175195],
                                ['SWAP', date(2024, 4, 30), date(2062, 4, 28),
                                    '38Y', 13877, 0.024003297],
                                ['SWAP', date(2024, 4, 30), date(2063, 4, 30),
                                    '39Y', 14244, 0.023831818],
                                ['SWAP', date(2024, 4, 30), date(2064, 4, 30),
                                    '40Y', 14610, 0.02366],
                                ['SWAP', date(2024, 4, 30), date(2074, 4, 30),
                                    '50Y', 18262, 0.02208],
                                ['SWAP', date(2024, 4, 30), date(2084, 4, 28),
                                    '60Y', 21913, 0.02108]], dtype=object))
ir_eur_curve_6m.columns = ['type', 'start', 'maturity', 'tenor', 'daycount', 'quote']

ir_eur_curve_estr = pd.DataFrame(np.array([['CASH', date(2024, 4, 30), date(2024, 5, 2),
                            '1BD', 2, 0.03906],
                        ['CASH', date(2024, 4, 30), date(2024, 5, 3),
                            '2BD', 3, 0.03906],
                        ['CASH', date(2024, 4, 30), date(2024, 5, 6),
                            '3BD', 6, 0.039072261],
                        ['SWAP', date(2024, 4, 30), date(2024, 5, 7),
                            '1W', 7, 0.03909],
                        ['SWAP', date(2024, 4, 30), date(2024, 5, 14),
                            '2W', 14, 0.03911],
                        ['SWAP', date(2024, 4, 30), date(2024, 5, 21),
                            '3W', 21, 0.03912],
                        ['SWAP', date(2024, 4, 30), date(2024, 5, 30),
                            '1M', 30, 0.03912],
                        ['SWAP', date(2024, 4, 30), date(2024, 6, 28),
                            '2M', 59, 0.03841],
                        ['SWAP', date(2024, 4, 30), date(2024, 7, 30),
                            '3M', 91, 0.03785],
                        ['SWAP', date(2024, 4, 30), date(2024, 8, 30),
                            '4M', 122, 0.03752],
                        ['SWAP', date(2024, 4, 30), date(2024, 9, 30),
                            '5M', 153, 0.03717],
                        ['SWAP', date(2024, 4, 30), date(2024, 10, 30),
                            '6M', 183, 0.03677],
                        ['SWAP', date(2024, 4, 30), date(2024, 11, 29),
                            '7M', 213, 0.03646],
                        ['SWAP', date(2024, 4, 30), date(2024, 12, 30),
                            '8M', 244, 0.03615],
                        ['SWAP', date(2024, 4, 30), date(2025, 1, 30),
                            '9M', 275, 0.03582],
                        ['SWAP', date(2024, 4, 30), date(2025, 2, 28),
                            '10M', 304, 0.03554],
                        ['SWAP', date(2024, 4, 30), date(2025, 3, 31),
                            '11M', 335, 0.03525],
                        ['SWAP', date(2024, 4, 30), date(2025, 4, 30),
                            '1Y', 365, 0.03494],
                        ['SWAP', date(2024, 4, 30), date(2025, 5, 30),
                            '13M', 395, 0.0345828],
                        ['SWAP', date(2024, 4, 30), date(2025, 6, 30),
                            '14M', 426, 0.034256265],
                        ['SWAP', date(2024, 4, 30), date(2025, 7, 30),
                            '15M', 456, 0.03393],
                        ['SWAP', date(2024, 4, 30), date(2025, 8, 29),
                            '16M', 486, 0.03363838],
                        ['SWAP', date(2024, 4, 30), date(2025, 9, 30),
                            '17M', 518, 0.033356217],
                        ['SWAP', date(2024, 4, 30), date(2025, 10, 30),
                            '18M', 548, 0.03308],
                        ['SWAP', date(2024, 4, 30), date(2025, 11, 28),
                            '19M', 577, 0.03283361],
                        ['SWAP', date(2024, 4, 30), date(2025, 12, 30),
                            '20M', 609, 0.032581264],
                        ['SWAP', date(2024, 4, 30), date(2026, 1, 30),
                            '21M', 640, 0.03237],
                        ['SWAP', date(2024, 4, 30), date(2026, 2, 27),
                            '22M', 668, 0.032174968],
                        ['SWAP', date(2024, 4, 30), date(2026, 3, 30),
                            '23M', 699, 0.031941762],
                        ['SWAP', date(2024, 4, 30), date(2026, 4, 30),
                            '2Y', 730, 0.03177],
                        ['SWAP', date(2024, 4, 30), date(2027, 4, 30),
                            '3Y', 1095, 0.02974],
                        ['SWAP', date(2024, 4, 30), date(2028, 4, 28),
                            '4Y', 1459, 0.02842],
                        ['SWAP', date(2024, 4, 30), date(2029, 4, 30),
                            '5Y', 1826, 0.02763],
                        ['SWAP', date(2024, 4, 30), date(2030, 4, 30),
                            '6Y', 2191, 0.02721],
                        ['SWAP', date(2024, 4, 30), date(2031, 4, 30),
                            '7Y', 2556, 0.02702],
                        ['SWAP', date(2024, 4, 30), date(2032, 4, 30),
                            '8Y', 2922, 0.02695],
                        ['SWAP', date(2024, 4, 30), date(2033, 4, 29),
                            '9Y', 3286, 0.02701],
                        ['SWAP', date(2024, 4, 30), date(2034, 4, 28),
                            '10Y', 3650, 0.02712],
                        ['SWAP', date(2024, 4, 30), date(2035, 4, 30),
                            '11Y', 4017, 0.027265194],
                        ['SWAP', date(2024, 4, 30), date(2036, 4, 30),
                            '12Y', 4383, 0.02743],
                        ['SWAP', date(2024, 4, 30), date(2037, 4, 30),
                            '13Y', 4748, 0.027587057],
                        ['SWAP', date(2024, 4, 30), date(2038, 4, 30),
                            '14Y', 5113, 0.02771706],
                        ['SWAP', date(2024, 4, 30), date(2039, 4, 29),
                            '15Y', 5477, 0.0278],
                        ['SWAP', date(2024, 4, 30), date(2040, 4, 30),
                            '16Y', 5844, 0.027820872],
                        ['SWAP', date(2024, 4, 30), date(2041, 4, 30),
                            '17Y', 6209, 0.027785126],
                        ['SWAP', date(2024, 4, 30), date(2042, 4, 30),
                            '18Y', 6574, 0.027702761],
                        ['SWAP', date(2024, 4, 30), date(2043, 4, 30),
                            '19Y', 6939, 0.027584793],
                        ['SWAP', date(2024, 4, 30), date(2044, 4, 29),
                            '20Y', 7304, 0.02744],
                        ['SWAP', date(2024, 4, 30), date(2045, 4, 28),
                            '21Y', 7668, 0.027277185],
                        ['SWAP', date(2024, 4, 30), date(2046, 4, 30),
                            '22Y', 8035, 0.027101559],
                        ['SWAP', date(2024, 4, 30), date(2047, 4, 30),
                            '23Y', 8400, 0.026917431],
                        ['SWAP', date(2024, 4, 30), date(2048, 4, 30),
                            '24Y', 8766, 0.026728034],
                        ['SWAP', date(2024, 4, 30), date(2049, 4, 30),
                            '25Y', 9131, 0.02654],
                        ['SWAP', date(2024, 4, 30), date(2050, 4, 29),
                            '26Y', 9495, 0.026354904],
                        ['SWAP', date(2024, 4, 30), date(2051, 4, 28),
                            '27Y', 9859, 0.026174621],
                        ['SWAP', date(2024, 4, 30), date(2052, 4, 30),
                            '28Y', 10227, 0.025999527],
                        ['SWAP', date(2024, 4, 30), date(2053, 4, 30),
                            '29Y', 10592, 0.025830481],
                        ['SWAP', date(2024, 4, 30), date(2054, 4, 30),
                            '30Y', 10957, 0.02567],
                        ['SWAP', date(2024, 4, 30), date(2059, 4, 30),
                            '35Y', 12783, 0.024965548],
                        ['SWAP', date(2024, 4, 30), date(2064, 4, 30),
                            '40Y', 14610, 0.02435],
                        ['SWAP', date(2024, 4, 30), date(2074, 4, 30),
                            '50Y', 18262, 0.02319],
                        ['SWAP', date(2024, 4, 30), date(2084, 4, 28),
                            '60Y', 21913, 0.02234]], dtype=object) )
ir_eur_curve_estr.columns = ['type', 'start', 'maturity', 'tenor', 'daycount', 'quote']

In [4]:
rates = ir_eur_curve_estr['quote'].values
times = ir_eur_curve_estr['daycount'].values/365

rates_6m = ir_eur_curve_6m['quote'].values
times_6m = ir_eur_curve_6m['daycount'].values/365

In [5]:
estr_curve = tq.RateCurve(times, rates)
eur6m_curve = tq.RateCurve(times_6m, rates_6m)

In [6]:
# instance of the hull-white model for 1M curve simulation
mean_rev = 0.02
sigma = 0.045
hw = tq.HullWhiteProcess(mean_rev, sigma, market_curve=estr_curve)
hw_kernel = tq.GaussianRateKernel1D(hw)

# simulate short rate and discount curve 
paths = int(1e6) 
r_tensor, zb_tensor, grid = hw_kernel.rate_tensor(paths,
                                                  last_grid_time=1,
                                                  time_steps=2) # evaluation_date + 1y
# Reshape the tensor and create a discount curve object
reshaped_tensor = tf.reshape(zb_tensor, shape=(zb_tensor.shape[1], paths, 1))
rate_curve_tensor = tq.DiscountCurveSimple(times, reshaped_tensor)

# Fixed coupon prices

In [7]:
d1 = calendar.advance(evaluation_date,
                         6,
                         tq.TimeUnit.Months,
                         tq.BusinessDayConvention.ModifiedFollowing)
nominal = 1e6
fixed_coupon = tq.FixedCoupon(d1,
                              nominal,
                              accrual_start_date= evaluation_date,
                              accrual_end_date= d1,
                              ref_period_start= evaluation_date,
                              ref_period_end= d1,
                              r= 0.02,
                              daycounter = daycounter)

## prezzo di un singolo coupon

In [8]:
fixed_coupon_pricer = tq.FixedCouponDiscounting(fixed_coupon)
# price single coupon
fixed_coupon_pricer.price(estr_curve, evaluation_date)

<tf.Tensor: shape=(), dtype=float64, numpy=9978.535430352356>

## prezzo dello stesso coupon con 1M curve differenti

In [9]:
# price with tensor curves
fixed_coupon_pricer.price(rate_curve_tensor, evaluation_date)

<tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
array([[10006.05654299],
       [ 9884.64385805],
       [ 9900.84878959],
       ...,
       [10109.83948039],
       [10000.05813881],
       [10020.66606391]])>

## prezzo dello stesso coupon con 1M curve differenti a 50 date

In [10]:
# price with tensor curves for 50 dates
date_list = [evaluation_date] *50
[fixed_coupon_pricer.price(rate_curve_tensor, d) for d in date_list]

[<tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
 array([[10006.05654299],
        [ 9884.64385805],
        [ 9900.84878959],
        ...,
        [10109.83948039],
        [10000.05813881],
        [10020.66606391]])>,
 <tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
 array([[10006.05654299],
        [ 9884.64385805],
        [ 9900.84878959],
        ...,
        [10109.83948039],
        [10000.05813881],
        [10020.66606391]])>,
 <tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
 array([[10006.05654299],
        [ 9884.64385805],
        [ 9900.84878959],
        ...,
        [10109.83948039],
        [10000.05813881],
        [10020.66606391]])>,
 <tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
 array([[10006.05654299],
        [ 9884.64385805],
        [ 9900.84878959],
        ...,
        [10109.83948039],
        [10000.05813881],
        [10020.66606391]])>,
 <tf.Tensor: shape=(1000000, 1), dtype=float64, numpy=
 array([[10006.05654299],
        [ 9

## AD sensitivity

In [11]:
pv, tape = fixed_coupon_pricer.price_aad(estr_curve, evaluation_date)

In [12]:
sensitivities = tape.gradient(pv, [estr_curve.rates])

In [13]:
sensy = pd.DataFrame([estr_curve.pillars.tolist(), sensitivities[0]]).T
sensy.columns = ['time', 'sensitivity']
sensy[sensy['time'] > 0.3].head(10)

time  sensitivity
9   0.334247          NaN
10  0.419178          NaN
11  0.501370          NaN
12  0.583562          NaN
13  0.668493          NaN
14  0.753425          NaN
15  0.832877          NaN
16  0.917808          NaN
17  1.000000          NaN
18  1.082192          NaN